version: '3'

networks:
  hyp-net:
    # If network is created with deplyment, Chaincode container cannot connect to network
    # as the created network name is '<STACK NAME>_hyperledger-ov'.
    # But chaincode container will attempt to connect 'hyperledger-ov' network
    external:
      name: hyp-net

services:

  # DipSup login microservice
  loginWebAppNaturalPersons:
    image: endimion13/eidas-gr-isswebapp:1.3.2
    ports:
      - 8080:8090
      - 8090:8090
      - 9080:8090
    environment:
       - EIDAS_PROPERTIES=CurrentFamilyName,CurrentGivenName,DateOfBirth,PersonIdentifier
<<<<<<< HEAD
       - SP_FAIL_PAGE=https://195.251.134.246/loginFail
       #- SP_SUCCESS_PAGE=http://138.68.103.237/loginSuccess
       - SP_SUCCESS_PAGE=http://195.251.134.246/loginSuccessReact
=======
       - SP_FAIL_PAGE=http://dss.aegean.gr/
       #- SP_SUCCESS_PAGE=http://138.68.103.237/loginSuccess
       - SP_SUCCESS_PAGE=http://dss.aegean.gr/loginSuccessReact
>>>>>>> 06826a8fb29a93314e4416c8b03911d0bcdd3d36
       - SP_LOGO=http://excellence.minedu.gov.gr/thales/sites/default/files/Logo-Aegean.png
       - ISS_URL=http://84.205.248.180/ISSPlus/ValidateToken
       - SP_ID=sp4
       - SP_SECRET=secret
<<<<<<< HEAD
       - AUTH_DURATION=2800 
=======
       - AUTH_DURATION=3800
>>>>>>> 06826a8fb29a93314e4416c8b03911d0bcdd3d36
    networks:
      hyp-net:
        aliases:
          - loginWeb


  loginWebAppLegalPersons:
  #container_name: loginWebApp
    image: endimion13/eidas-gr-loginwebapp:3.1
    ports:
      - 9081:8090
      - 9091:8090
    environment:
      - EIDAS_PROPERTIES=http://eidas.europa.eu/attributes/legalperson/representative/LegalName,http://eidas.europa.eu/attributes/legalperson/representative/LegalPersonIdentifier
      - SP_FAIL_PAGE=http://dss.aegean.gr/
      #- SP_BACKEND=
      - SP_SUCCESS_PAGE=http://dss.aegean.gr/loginSuccess
      - SP_METADATA_URL=http://dss.aegean.gr:9091/metadata
      - SP_RETURN_URL=http://dss.aegean.gr:9091/eidasResponse
      - SP_LOGO=http://trc.aiest.org/wp-content/uploads/2013/04/university-of-the-aegean.png
      - SP_CONFIG_REPOSITORY=/configEidas/
    volumes:
      - /configEidas:/configEidas
      - /keystore:/keystore
    networks:
      hyp-net:
        aliases:
          - loginWeb2


  # email microservice
  postfix:
    image: catatnight/postfix
    ports:
      - 25:25
    environment:
      - maildomain=dss.aegean.gr
      - smtp_user=user:pwd
    networks:
      hyp-net:
        aliases:
          - postfixWebApp
<<<<<<< HEAD
    deploy:
      placement:
        constraints: [node.role == manager]

=======
>>>>>>> 06826a8fb29a93314e4416c8b03911d0bcdd3d36
