version: '3'

services:

  loginWebApp2:
    image: endimion13/toop-eid:0.3.4
    ports:
      - 9080:8090
      - 9090:8090
#      - 8443:8443
    environment:
      - EIDAS_PROPERTIES=http://eidas.europa.eu/attributes/naturalperson/CurrentFamilyName,http://eidas.europa.eu/attributes/naturalperson/CurrentGivenName,http://eidas.europa.eu/attributes/naturalperson/DateOfBirth,http://eidas.europa.eu/attributes/naturalperson/PersonIdentifier
      - SP_FAIL_PAGE= http://www.host.com/authfail
      - SP_SUCCESS_PAGE=http://www.host.com/loginSuccess
      - SP_METADATA_URL=http://www.host.com:9090/metadata
      - SP_RETURN_URL=http://www.host.com:9090/eidasResponse
      - SP_LOGO=https://www.euritas.eu/wp-content/uploads/2017/10/TOOP-Logo-1024x368.png
      - SP_CONFIG_REPOSITORY=/configEidas/

    volumes:
      - /configEidas:/configEidas
